SST2:
  lr: 0.000001
  batch_size: 32
  model_load_dir: '.'
  n_epochs: 30
  kwargs_path: './pretrain_model_SST-2/parameters.json'
  pretrain_dir: './pretrain_model_SST-2/weights'
  model_save_dir: './pretrain_model_SST'
  task: 'SST-2'
  vocab_size: 49624
  type_vocab_size: 2
  max_position_embeddings: 512  
  hidden_size: 768
  intermediate_size: 3072
  chunk_size_feed_forward: 0
  num_layers: 12  
  nheads: 12
  activation: "gelu"
  pad_token_id: 1
  layer_norm_eps: 0.00001
  attn_dropout: 0
  hidden_dropout: 0
  position_embedding_type: "absolute"
  is_decoder: False
  add_pooling_layer: True
  add_cross_attention: False